/* 
 * TABLE: [dbo].[Birth] 
 */

CREATE TABLE [dbo].[Birth](
    [BirthCertificateNumber]                                           int               NOT NULL,
    [HealthcareActivityID]                                         int               NOT NULL,
    [AttendantTypeName]                                                varchar(256)      NULL,
    [BirthPluralityNumber]                                             decimal(18, 9)    NULL,
    [BirthOrderNumber]                                                 decimal(18, 9)    NULL,
    [BirthChildsSexID]                                             varchar(256)      NULL,
    [BirthWeightGrams]                                                 int               NULL,
    [BirthWeightOunces]                                                decimal(18, 9)    NULL,
    [BirthWeightPriority]                                              varchar(256)      NULL,
    [GestationEstimateWeeks]                                           int               NULL,
    [GestationObstetricEstimateWeeks]                                  int               NULL,
    [GestationClinicalEstimateWeeks]                                   int               NULL,
    [APGAR5minNumber]                                                  decimal(18, 9)    NULL,
    [APGAR10minNumber]                                                 decimal(18, 9)    NULL,
    [PrenatalVisitCount]                                               int               NULL,
    [MotherTransferredFlag]                                            char(1)           NULL,
    [MotherReceivedWICFlag]                                            char(1)           NULL,
    [MotherReceivedPrenatalCareFlag]                                   char(1)           NULL,
    [FirstPrenatalVisitDate]                                           datetime          NULL,
    [LastPrenatalVisitDate]                                            datetime          NULL,
    [PregancyWeightGainedPounds]                                       decimal(18, 9)    NULL,
    [PreviousPregnanciesLivingCount]                                   int               NULL,
    [PreviousPregnanciesDeadCount]                                     int               NULL,
    [LastLiveBirthDate]                                                datetime          NULL,
    [PreviousTerminationsCount]                                        int               NULL,
    [LastTerminationDate]                                              datetime          NULL,
    [PrePregnancyCigarettesPerDayCount]                                int               NULL,
    [FirstTrimesterCigarettesPerDayCount]                              int               NULL,
    [SecondTrimesterCigarettesPerDayCount]                             int               NULL,
    [ThirdTrimesterCigarettesPerDayCount]                              int               NULL,
    [PrePregnancyDrinksPerWeekCount]                                   int               NULL,
    [FirstTrimesterDrinksPerWeekCount]                                 int               NULL,
    [SecondTrimesterDrinksPerWeekCount]                                int               NULL,
    [ThridTrimesterDrinksPerWeekCount]                                 int               NULL,
    [LastNormalMensisDate]                                             datetime          NULL,
    [InfantTransferredWithin24HoursOfDeliveryFlag]                     char(1)           NULL,
    [InfantReceivingBreastMilkAtDischargeFlag]                         char(1)           NULL,
    [PrenatalHepatitisBScreenFlag]                                     char(1)           NULL,
    [PrenatalHivScreenFlag]                                            char(1)           NULL,
    [InfantReceivedHepatitisBImmunizationFlag]                         char(1)           NULL,
    [InfantReceivedHepatitisBImmunizationDate]                         datetime          NULL,
    [RiskFactorsPrepregnancyDiabetesFlag]                              char(1)           NULL,
    [RiskFactorsGestationalDiabetesFlag]                               char(1)           NULL,
    [RiskFactorsPrepregnancyHypertensionFlag]                          char(1)           NULL,
    [RiskFactorsGestationalHypertensionFlag]                           char(1)           NULL,
    [RiskFactorsEclampsiaFlag]                                         char(1)           NULL,
    [RiskFactorsHellpSyndromeFlag]                                     char(1)           NULL,
    [RiskFactorsPreviousPretermBirthFlag]                              char(1)           NULL,
    [RiskFactorsPreviousInfantOver4000GramsFlag]                       char(1)           NULL,
    [RiskFactorsOtherPreviousPoorOutcomeFlag]                          char(1)           NULL,
    [RiskFactorsPregnancyResultedFromInfertilityTreatmentFlag]         char(1)           NULL,
    [RiskFactorsInfertilityTreatmentAsDrugsInseminationFlag]           char(1)           NULL,
    [RiskFactorsAssistedReproductiveTechnologyFlag]                    char(1)           NULL,
    [RiskFactorsPreviousCesareanFlag]                                  char(1)           NULL,
    [RiskFactorsNumberOfPreviousCesareansFlag]                         char(1)           NULL,
    [RiskFactorsAsthmaFlag]                                            char(1)           NULL,
    [RiskFactorsGenitalHerpesFlag]                                     char(1)           NULL,
    [RiskFactorsOtherFlag]                                             char(1)           NULL,
    [RiskFactorsNoneFlag]                                              char(1)           NULL,
    [RiskFactorsUnknownFlag]                                           char(1)           NULL,
    [PrenatalSyphilisScreenFlag]                                       char(1)           NULL,
    [InfectionsGonorrheaFlag]                                          char(1)           NULL,
    [InfectionsChlamydiaFlag]                                          char(1)           NULL,
    [InfectionsCytomegalovirusFlag]                                    char(1)           NULL,
    [InfectionsHepatitisBFlag]                                         char(1)           NULL,
    [InfectionsHepatitisCFlag]                                         char(1)           NULL,
    [InfectionsHivAidsFlag]                                            char(1)           NULL,
    [InfectionsHerpesSimplexVirusFlag]                                 char(1)           NULL,
    [InfectionsRubellaFlag]                                            char(1)           NULL,
    [InfectionsBacterialVaginosisFlag]                                 char(1)           NULL,
    [InfectionsGroupBStrepFlag]                                        char(1)           NULL,
    [InfectionsOtherFlag]                                              char(1)           NULL,
    [InfectionsNoneFlag]                                               char(1)           NULL,
    [InfectionsUnknownFlag]                                            char(1)           NULL,
    [ObProceduresCervicalCerclageFlag]                                 char(1)           NULL,
    [ObProceduresTocolysisFlag]                                        char(1)           NULL,
    [ObProceduresExternalCephalicVersionSuccessfulFlag]                char(1)           NULL,
    [ObProceduresExternalCephalicVersionFailedFlag]                    char(1)           NULL,
    [ObProceduresOtherFlag]                                            char(1)           NULL,
    [ObProceduresNoneFlag]                                             char(1)           NULL,
    [ObProceduresUnknownFlag]                                          char(1)           NULL,
    [OnsetOfLaborPrematureRuptureOfMembranesFlag]                      char(1)           NULL,
    [OnsetOfLaborPrecipitousFlag]                                      char(1)           NULL,
    [OnsetOfLaborProlongedFlag]                                        char(1)           NULL,
    [OnsetOfLaborOtherFlag]                                            char(1)           NULL,
    [OnsetOfLaborNoneFlag]                                             char(1)           NULL,
    [OnsetOfLaborUnknownFlag]                                          char(1)           NULL,
    [LaborDeliveryInductionOfLaborFlag]                                char(1)           NULL,
    [LaborDeliveryAugmentationOfLaborFlag]                             char(1)           NULL,
    [LaborDeliveryNonVertexPresentationFlag]                           char(1)           NULL,
    [LaborDeliverySteroidsForFetalLungMaturationReceivedByMotherFlag]  char(1)           NULL,
    [LaborDeliveryAntibioticsReceivedByMotherDuringLaborFlag]          char(1)           NULL,
    [LaborDeliveryClinicalChorioamnionitisFlag]                        char(1)           NULL,
    [LaborDeliveryModerateHeavyMeconiumStainingOfAmnioticFluidFlag]    char(1)           NULL,
    [LaborDeliveryFetalIntoleranceOfLaborFlag]                         char(1)           NULL,
    [LaborDeliveryEpiduralOrSpinalAnesthesiaDuringLaborFlag]           char(1)           NULL,
    [LaborDeliveryOtherFlag]                                           char(1)           NULL,
    [LaborDeliveryNoneFlag]                                            char(1)           NULL,
    [LaborDeliveryUnknownFlag]                                         char(1)           NULL,
    [MethodForcepsAttemptedFlag]                                       char(1)           NULL,
    [MethodVacuumExtractionAttemptedFlag]                              char(1)           NULL,
    [FetalPresentationCephalicFlag]                                    char(1)           NULL,
    [FetalPresentationBreechFlag]                                      char(1)           NULL,
    [FetalPresentationOtherFlag]                                       char(1)           NULL,
    [FetalPresentationUnknownFlag]                                     char(1)           NULL,
    [TrialOfLaborPriorToCesareanFlag]                                  char(1)           NULL,
    [RouteMethodVaginalSpontaneousFlag]                                char(1)           NULL,
    [RouteMethodVaginalForcepsFlag]                                    char(1)           NULL,
    [RouteMethodVaginalVacuumFlag]                                     char(1)           NULL,
    [RouteMethodCesareanFlag]                                          char(1)           NULL,
    [RouteMethodUnknownFlag]                                           char(1)           NULL,
    [MaternalMorbidityMaternalTransfusionFlag]                         char(1)           NULL,
    [MaternalMorbidity3RdOr4ThDegreePerinealLacerationFlag]            char(1)           NULL,
    [MaternalMorbidityRupturedUterusFlag]                              char(1)           NULL,
    [MaternalMorbidityUnplannedHysterectomyFlag]                       char(1)           NULL,
    [MaternalMorbidityAdmissionToIntensiveCareFlag]                    char(1)           NULL,
    [MaternalMorbidityUnplannedOperatingRoomProcedureFlag]             char(1)           NULL,
    [MaternalMorbidityVbacFlag]                                        char(1)           NULL,
    [MaternalMorbidityAbruptioPlacentaFlag]                            char(1)           NULL,
    [MaternalMorbidityPlacentaPreviaFlag]                              char(1)           NULL,
    [MaternalMorbidityCephalopelvicDisproportionFlag]                  char(1)           NULL,
    [MaternalMorbidityCordProlapseFlag]                                char(1)           NULL,
    [MaternalMorbidityOtherFlag]                                       char(1)           NULL,
    [MaternalMorbidityNoneFlag]                                        char(1)           NULL,
    [MaternalMorbidityUnknownFlag]                                     char(1)           NULL,
    [AbnormalConditionsAssistedVentilationFollowingDeliveryFlag]       char(1)           NULL,
    [AbnormalConditionsAssistedVentilationForOver6HoursFlag]           char(1)           NULL,
    [AbnormalConditionsSupplementalOxygenFlag]                         char(1)           NULL,
    [AbnormalConditionsNicuAdmissionFlag]                              char(1)           NULL,
    [AbnormalConditionsSurfactantReplacementTherapyFlag]               char(1)           NULL,
    [AbnormalConditionsAntibioticsForSuspectedNeonatalSepsisFlag]      char(1)           NULL,
    [AbnormalConditionsSeizureFlag]                                    char(1)           NULL,
    [AbnormalConditionsBirthInjuryFlag]                                char(1)           NULL,
    [AbnormalConditionsHyalineMembraneDiseaseRdsFlag]                  char(1)           NULL,
    [AbnormalConditionsMeconiumAspirationSyndromeFlag]                 char(1)           NULL,
    [AbnormalConditionsHypoglycemiaFlag]                               char(1)           NULL,
    [AbnormalConditionsHyperbilirubinemiaFlag]                         char(1)           NULL,
    [AbnormalConditionsOtherFlag]                                      char(1)           NULL,
    [AbnormalConditionsNoneFlag]                                       char(1)           NULL,
    [AbnormalConditionsUnknownFlag]                                    char(1)           NULL,
    [CongenitalAnomaliesAnencephalyFlag]                               char(1)           NULL,
    [CongenitalAnomaliesMeningomyeloceleSpinaBifidaFlag]               char(1)           NULL,
    [CongenitalAnomaliesCyanoticCongenitalHeartDiseaseFlag]            char(1)           NULL,
    [CongenitalAnomaliesCongenitalDiaphragmaticHerniaFlag]             char(1)           NULL,
    [CongenitalAnomaliesOmphaloceleFlag]                               char(1)           NULL,
    [CongenitalAnomaliesGastroschisisFlag]                             char(1)           NULL,
    [CongenitalAnomaliesLimbReductionDefectFlag]                       char(1)           NULL,
    [CongenitalAnomaliesCleftLipFlag]                                  char(1)           NULL,
    [CongenitalAnomaliesCleftPalateFlag]                               char(1)           NULL,
    [CongenitalAnomaliesDownSyndromeFlag]                              char(1)           NULL,
    [CongenitalAnomaliesDownSyndromeConfirmedFlag]                     char(1)           NULL,
    [CongenitalAnomaliesDownSyndromePendingFlag]                       char(1)           NULL,
    [CongenitalAnomaliesOtherChromosomalDisorderFlag]                  char(1)           NULL,
    [CongenitalAnomaliesOtherChromosomalDisorderConfirmedFlag]         char(1)           NULL,
    [CongenitalAnomaliesOtherChromosomalDisorderPendingFlag]           char(1)           NULL,
    [CongenitalAnomaliesHypospadiasFlag]                               char(1)           NULL,
    [CongenitalAnomaliesUrogenitalAnomaliesFlag]                       char(1)           NULL,
    [CongenitalAnomaliesCirculatoryRespiratoryAnomaliesFlag]           char(1)           NULL,
    [CongenitalAnomaliesMusculoskeletalAnomaliesFlag]                  char(1)           NULL,
    [CongenitalAnomaliesOtherFlag]                                     char(1)           NULL,
    [CongenitalAnomaliesNotStatedFlag]                                 char(1)           NULL,
    [CongenitalAnomaliesNoneFlag]                                      char(1)           NULL,
    [CongenitalAnomaliesUnknownFlag]                                   char(1)           NULL,
    [DataSourceID]                                                     int               NOT NULL,
    [LoadID]                                                           int               NOT NULL,
    [RowStartDate]                                                     datetime          NOT NULL,
    [RowEndDate]                                                       datetime          NULL,
    [RowCurrentFlag]                                                   int               NULL,
    CONSTRAINT [IDX_PK_Birth1] PRIMARY KEY NONCLUSTERED ([HealthcareActivityID], [BirthCertificateNumber])
)
GO
/* 
 * TABLE: [dbo].[Birth] 
 */

ALTER TABLE [dbo].[Birth] ADD CONSTRAINT [FK_HealthcareActivity_Birth] 
    FOREIGN KEY ([HealthcareActivityID])
    REFERENCES [dbo].[HealthcareActivity]([HealthcareActivityID])
